String readString;

void setup() 
{
  Serial.begin(9600);
}

void loop()
{
  while (Serial.available()) {
    delay(3);  
    char c = Serial.read();
    readString += c; 
  }
  if (readString.length() > 0) {
    if (readString == "start") {
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(50);
      Serial.println("Serial.println(\"this is a very long string\");");
      delay(50);
      Serial.println("Serial.println(\"this is another long string\");");
      delay(50);
      Serial.println("Serial.println(\"hello\");");
      delay(1000);
      Serial.println("stop");
    }
    readString="";
  }
} 


